version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - /var/www/html/NewsletterUpdate:/var/www/NewsletterUpdate/
    container_name: ubuntu-php
  web:
    image: nginx:latest
    working_dir: /var/www
    volumes:
      - /var/www/html/NewsletterUpdate:/var/www/NewsletterUpdate/
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5000:80"
    depends_on:
      - app
    container_name: nginx

